"""removed constraints in readings

Revision ID: 311019ef4ddc
Revises: 327d240dc5a2
Create Date: 2024-05-21 20:14:07.510127

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '311019ef4ddc'
down_revision = '327d240dc5a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('readings', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('past_card_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('present_card_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('future_card_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('readings', schema=None) as batch_op:
        batch_op.alter_column('future_card_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('present_card_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('past_card_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
