"""added updated at for lessonstats

Revision ID: 9ba9341b48b3
Revises: 92ed0254065b
Create Date: 2024-05-20 11:01:26.681563

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ba9341b48b3'
down_revision = '92ed0254065b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lessonStatistics', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lessonStatistics', schema=None) as batch_op:
        batch_op.drop_column('updated_at')

    # ### end Alembic commands ###
