"""created lessonQuestions model

Revision ID: fb6d30bf0cea
Revises: f90c02139382
Create Date: 2024-05-23 15:15:26.310479

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb6d30bf0cea'
down_revision = 'f90c02139382'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lessonQuestions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lesson_id', sa.Integer(), nullable=False),
    sa.Column('question', sa.String(), nullable=True),
    sa.Column('answer1', sa.String(), nullable=True),
    sa.Column('answer2', sa.String(), nullable=True),
    sa.Column('answer3', sa.String(), nullable=True),
    sa.Column('answer4', sa.String(), nullable=True),
    sa.Column('correct_answer', sa.String(), nullable=True),
    sa.Column('explanation', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], name=op.f('fk_lessonQuestions_lesson_id_lessons')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lessonQuestions')
    # ### end Alembic commands ###
